{{- if .Values.preSyncHook.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-check
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.preSyncHook.serviceAccountName }}
      containers:
        - name: pre-check
          image: {{ .Values.preSyncHook.image }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "[INFO] Starting pre-sync cluster validation..."

              # Verificar disponibilidad de nodos
              if ! kubectl get nodes > /dev/null 2>&1; then
                echo "[ERROR] Cluster validation failed. Unable to retrieve node information."
                exit 1
              fi

              echo "[INFO] Cluster validation completed successfully. Proceeding with deployment."
      restartPolicy: Never
  backoffLimit: {{ .Values.preSyncHook.backoffLimit }}
{{- end }}

