apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pre-sync-check-role
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]

