apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollout-k8s.fullname" . }}
  labels:
    {{- include "rollout-k8s.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  {{- if .Values.metrics.enabled }}
    - name: {{ .Values.metrics.portName }}
      port: {{ .Values.metrics.port }}
      targetPort: http
      protocol: TCP
  {{- end }}
  selector:
    app: {{ .Release.Name }}
